# Generated by Django 5.1 on 2024-09-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
