# Generated by Django 5.1 on 2024-09-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_product_image_alter_product_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
