# Generated by Django 5.1.1 on 2024-10-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_product_image_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
